server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidation123456789}
  expiration: 86400000

logging:
  level:
    com.tasktracker.auth: DEBUG
    org.springframework: WARN
    org.springframework.security: INFO      # перезапишет DEBUG выше, если хочешь меньше Security логов
    org.hibernate: WARN
    org.hibernate.SQL: DEBUG                # но SQL оставить
    org.hibernate.orm.jdbc.bind: WARN       # убрать bind parameters спам
    org.apache.kafka: WARN
    io.netty: WARN
    root: WARN