spring:
  application:
    name: task-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/task_db}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: task-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidation123456789}

services:
  auth-url: ${AUTH_SERVICE_URL:http://localhost:8081}

logging:
  level:
    com.example: DEBUG

    # MongoDB
    org.springframework.data.mongodb: WARN
    org.mongodb.driver: WARN

    # Kafka
    org.springframework.kafka: WARN
    org.apache.kafka: WARN

    # Security/JWT
    org.springframework.security: WARN
    org.springframework.web: WARN

    root: DEBUG